apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-secrets
type: Opaque
data:
  DATABASE_USER: {{ .Values.database.user | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.database.rootPassword | b64enc | quote }}
