apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-catgif
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-catgif
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-catgif
    spec:
      containers:
      - name: catgif
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        env:
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-app-config
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-app-config
              key: DATABASE_PORT
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-app-config
              key: DATABASE_NAME
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-app-config
              key: PORT
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-app-secrets
              key: DATABASE_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-app-secrets
              key: DATABASE_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-catgif-service
spec:
  selector:
    app: {{ .Release.Name }}-catgif
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
