apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-init-sql-configmap
data:
  init.sql: |
    -- Use the target database
    CREATE DATABASE IF NOT EXISTS {{ .Values.database.name }};
    USE {{ .Values.database.name }};

    -- Create the images table
    CREATE TABLE IF NOT EXISTS images (
        id INT AUTO_INCREMENT PRIMARY KEY,
        url VARCHAR(255) NOT NULL
    );

    -- Insert initial data
    {{- range .Values.database.seedData }}
    INSERT INTO images (url) VALUES ("{{ . }}");
    {{- end }}
