apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: catgif-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: catgif
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
