apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  DATABASE_USER: Y2F0Z2lmX3VzZXI=  # base64 encoded value of "catgif_user"
  DATABASE_PASSWORD: Y2F0Z2lmX3Bhc3N3b3Jk  # base64 encoded value of "catgif_password"
  MYSQL_ROOT_PASSWORD: eW91cnBhc3N3b3Jk  # base64 encoded value of "yourpassword"
