# Use the official Python 3.8 image as the base image for the container.
FROM python:3.8

# Set the working directory inside the container to /usr/src/app.
# All subsequent commands will be executed from this directory.
WORKDIR /usr/src/app

# Copy all files from the current directory (on the host) to the working directory in the container.
COPY . .

# Install the required dependencies listed in the requirements.txt file.
# The --no-cache-dir flag prevents unnecessary caching to keep the image size smaller.
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 5000 so that the Flask application can be accessed externally.
EXPOSE 5000

# Define the command to run the application when the container starts.
CMD ["python", "./app.py"]
